# Generated by Django 2.2.6 on 2019-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0002_auto_20191001_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequestapplication',
            name='event_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
