# Generated by Django 2.2.6 on 2019-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0004_subteamtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBudgetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_required', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('negotiating', 'negotiating'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=50)),
            ],
        ),
    ]
