# Generated by Django 2.2.6 on 2019-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0005_extrabudgetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], default='full_time', max_length=50)),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
    ]
