# Generated by Django 2.2.6 on 2019-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0006_staffrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequestapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='eventrequestapplication',
            name='approved_by_admin_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequestapplication',
            name='approved_by_financial_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventrequestapplication',
            name='approved_by_senior_customer_service_officer',
            field=models.BooleanField(default=False),
        ),
    ]
