# Generated by Django 2.2.6 on 2019-10-07 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sep', '0007_auto_20191007_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteamtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subteam_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
