# Generated by Django 2.2.6 on 2019-10-07 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sep', '0009_auto_20191007_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequestapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
